// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: djinn.proto

package djinn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MagnificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *MagnificationRequest) Reset() {
	*x = MagnificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_djinn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MagnificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagnificationRequest) ProtoMessage() {}

func (x *MagnificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_djinn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagnificationRequest.ProtoReflect.Descriptor instead.
func (*MagnificationRequest) Descriptor() ([]byte, []int) {
	return file_djinn_proto_rawDescGZIP(), []int{0}
}

func (x *MagnificationRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MagnificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Types that are assignable to Type:
	//	*MagnificationResponse_SentimentResponse
	Type isMagnificationResponse_Type `protobuf_oneof:"type"`
}

func (x *MagnificationResponse) Reset() {
	*x = MagnificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_djinn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MagnificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagnificationResponse) ProtoMessage() {}

func (x *MagnificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_djinn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagnificationResponse.ProtoReflect.Descriptor instead.
func (*MagnificationResponse) Descriptor() ([]byte, []int) {
	return file_djinn_proto_rawDescGZIP(), []int{1}
}

func (x *MagnificationResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (m *MagnificationResponse) GetType() isMagnificationResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *MagnificationResponse) GetSentimentResponse() *MagnificationResponse_Sentiment {
	if x, ok := x.GetType().(*MagnificationResponse_SentimentResponse); ok {
		return x.SentimentResponse
	}
	return nil
}

type isMagnificationResponse_Type interface {
	isMagnificationResponse_Type()
}

type MagnificationResponse_SentimentResponse struct {
	SentimentResponse *MagnificationResponse_Sentiment `protobuf:"bytes,2,opt,name=sentiment_response,json=sentimentResponse,proto3,oneof"`
}

func (*MagnificationResponse_SentimentResponse) isMagnificationResponse_Type() {}

type MagnificationResponse_Sentiment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Positive float64 `protobuf:"fixed64,1,opt,name=positive,proto3" json:"positive,omitempty"`
	Negative float64 `protobuf:"fixed64,2,opt,name=negative,proto3" json:"negative,omitempty"`
}

func (x *MagnificationResponse_Sentiment) Reset() {
	*x = MagnificationResponse_Sentiment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_djinn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MagnificationResponse_Sentiment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagnificationResponse_Sentiment) ProtoMessage() {}

func (x *MagnificationResponse_Sentiment) ProtoReflect() protoreflect.Message {
	mi := &file_djinn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagnificationResponse_Sentiment.ProtoReflect.Descriptor instead.
func (*MagnificationResponse_Sentiment) Descriptor() ([]byte, []int) {
	return file_djinn_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MagnificationResponse_Sentiment) GetPositive() float64 {
	if x != nil {
		return x.Positive
	}
	return 0
}

func (x *MagnificationResponse_Sentiment) GetNegative() float64 {
	if x != nil {
		return x.Negative
	}
	return 0
}

var File_djinn_proto protoreflect.FileDescriptor

var file_djinn_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x6a, 0x69, 0x6e, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6c,
	0x61, 0x6e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x64, 0x6a, 0x69, 0x6e, 0x6e, 0x22, 0x2a, 0x0a, 0x14,
	0x4d, 0x61, 0x67, 0x6e, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xd9, 0x01, 0x0a, 0x15, 0x4d, 0x61, 0x67,
	0x6e, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x5f, 0x0a, 0x12, 0x73, 0x65, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x64, 0x6a, 0x69,
	0x6e, 0x6e, 0x2e, 0x4d, 0x61, 0x67, 0x6e, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x11, 0x73, 0x65, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x43, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x69, 0x76, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x32, 0x71, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x67, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x58, 0x0a,
	0x07, 0x4d, 0x61, 0x67, 0x6e, 0x69, 0x66, 0x79, 0x12, 0x23, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x64, 0x6a, 0x69, 0x6e, 0x6e, 0x2e, 0x4d, 0x61, 0x67, 0x6e, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x6c, 0x61, 0x6e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x64, 0x6a, 0x69, 0x6e, 0x6e, 0x2e, 0x4d, 0x61,
	0x67, 0x6e, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x16, 0x5a, 0x14, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x6a, 0x69, 0x6e, 0x6e, 0x3b, 0x64, 0x6a, 0x69, 0x6e, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_djinn_proto_rawDescOnce sync.Once
	file_djinn_proto_rawDescData = file_djinn_proto_rawDesc
)

func file_djinn_proto_rawDescGZIP() []byte {
	file_djinn_proto_rawDescOnce.Do(func() {
		file_djinn_proto_rawDescData = protoimpl.X.CompressGZIP(file_djinn_proto_rawDescData)
	})
	return file_djinn_proto_rawDescData
}

var file_djinn_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_djinn_proto_goTypes = []interface{}{
	(*MagnificationRequest)(nil),            // 0: langame.djinn.MagnificationRequest
	(*MagnificationResponse)(nil),           // 1: langame.djinn.MagnificationResponse
	(*MagnificationResponse_Sentiment)(nil), // 2: langame.djinn.MagnificationResponse.Sentiment
}
var file_djinn_proto_depIdxs = []int32{
	2, // 0: langame.djinn.MagnificationResponse.sentiment_response:type_name -> langame.djinn.MagnificationResponse.Sentiment
	0, // 1: langame.djinn.ConversationMagnifier.Magnify:input_type -> langame.djinn.MagnificationRequest
	1, // 2: langame.djinn.ConversationMagnifier.Magnify:output_type -> langame.djinn.MagnificationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_djinn_proto_init() }
func file_djinn_proto_init() {
	if File_djinn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_djinn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MagnificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_djinn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MagnificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_djinn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MagnificationResponse_Sentiment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_djinn_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*MagnificationResponse_SentimentResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_djinn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_djinn_proto_goTypes,
		DependencyIndexes: file_djinn_proto_depIdxs,
		MessageInfos:      file_djinn_proto_msgTypes,
	}.Build()
	File_djinn_proto = out.File
	file_djinn_proto_rawDesc = nil
	file_djinn_proto_goTypes = nil
	file_djinn_proto_depIdxs = nil
}
